### ISSUE TITLE
Comma dangle set incorrectly for node projects

### ISSUE THREAD

**Issue by johnhampton** [topagentnetwork/javascript#3]
No version of node can handle a comma at the end of a function parameter list. We need to update our rules to be more like this:

```json
      "comma-dangle": ["error", {
        "arrays": "always-multiline",
        "objects": "always-multiline",
        "functions": "never"
      }]
```

See http://eslint.org/docs/rules/comma-dangle for all comma-dangle options.

**Comment by shinzui** [comment]
I didn't even know you can have comma dangle for functions.

**Comment by johnhampton** [comment]
I didn't either until the eslint prettifier produced code that failed to run.

http://node.green/#trailing-commas-in-function-syntax
